version: "2.3"
services:
  kaggle:
    build:
     context: .
     shm_size: '32gb'
    shm_size: '32gb'
    container_name: nfl
    volumes:
     - ./:/work
    working_dir: /work
    runtime: nvidia
    ports:
     - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --port 8888 --allow-root --NotebookApp.notebook_dir='/work' --no-browser --LabApp.token=''
