seed: 42
img_size: 128
num_channels: 32
step_train: 32
step_pred: 8
epochs: 15
train_bs: 4 # 8
valid_bs: 16
lr: 0.0001
weight_decay: 0.000001
num_workers: 16
n_fold: 5
backbone: "resnext50"
feature_drop_out: 0.2
frame_drop_out: 0.4