seed: 42
img_size: 128
num_channels: 64
step_train: 64
step_pred: 64
epochs: 15
train_bs: 6
valid_bs: 6
lr: 0.0001
weight_decay: 0.000001
num_workers: 8
n_fold: 5
backbone: "resnext50"
feature_drop_out: 0.2
frame_drop_out: 0.4